server:
  port: 2001
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-2:1001/eureka/ #注册到中心地址，可配置多个。如：1000，1001两个注册中心（集群的方式）
spring:
  application:
    name: eureka-client-2

