#重试机制
feign:
  client:
    config:
#      default: # 全局生效
#        retryer: com.itchun.retryer.DefaultFeignRetry
      openfeign-2011-2: # 指定 【openfeign-2011-2】
        retryer: com.itchun.retryer.FeginRetry2011_2