#设置了。没卵子用
feign:
  httpclient: #httpclient客户端配置（全局）
    enabled: true
    connection-timeout: 1000 #连接超时时间(单位：毫秒)
    time-to-live: 900 #线程存活时间(单位：秒)
    max-connections: 200 #线程池最大连接数（全局）
    max-connections-per-route: 50 #线程池最大连接数（单个HOST）