server:
  port: 2012

spring:
  application:
    name: openfeign-client-group-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-1:1000/eureka/ #注册到中心地址，可配置多个。如：1000，1001两个注册中心（集群的方式）